version: '3'

networks:
  dev-docker_gokapnet:
    external: true
  my_network:
    driver: bridge

# platforms:
#   - linux/amd64

services:
  flask_app:
    build: .
#    image: 291621997224.dkr.ecr.ap-south-1.amazonaws.com/face-swap
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: gunicorn -b 0.0.0.0:5000 api:app
    environment:
      - PYTHONUNBUFFERED=TRUE
    networks:
      - dev-docker_gokapnet

  celery_worker:
#    image: 291621997224.dkr.ecr.ap-south-1.amazonaws.com/face-swap
    build: .
    # depends_on:
    #   - redis
    volumes:
      - .:/app
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER=redis://redis.gokapturehub.com:6379/0
    command: python -m celery -A tasks worker --loglevel=info
    networks:
      - dev-docker_gokapnet

  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./db:/data/db
  #   networks:
  #    - my_network

  redis_listener:
    build: ./redis-listener
    volumes:
      - ./redis-listener:/app
      - /app/node_modules
    ports:
      - "5002:5001"
    command: npm start
    networks:
      - dev-docker_gokapnet

  whatsapp_api:
    image: public.ecr.aws/t1n3q9p8/gokapturehub-misc
    container_name: whatsapp_api
    platform: linux/amd64
    restart: always
    ports:
      - "5003:3000"
    networks:
      - dev-docker_gokapnet
