version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - mynetwork

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:

  # whatsapp_api:
  #   image: public.ecr.aws/t1n3q9p8/gokapturehub-misc
  #   container_name: whatsapp_api
  #   restart: always
  #   ports:
  #     - "3000:3000"