version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: gunicorn -b 0.0.0.0:5000 api:app
    environment:
      - PYTHONUNBUFFERED=TRUE
      # - FLASK_APP=app.py
    #   - FLASK_ENV=development

  redis:
    image: redis:latest

  celery_worker:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER=redis://redis:6379/0
    command: python -m celery -A tasks worker --loglevel=info

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db

  redis_listener:
    build: ./redis-listener
    depends_on:
      - redis
    ports:
      - "5001:5001"
    volumes:
      - ./redis-listener:/app
    command: npm start

  # whatsapp_api:
  #   image: public.ecr.aws/t1n3q9p8/gokapturehub-misc
  #   container_name: whatsapp_api
  #   restart: always
  #   ports:
  #     - "3000:3000"